### ISSUE TITLE
mdsvex-relative-images

### ISSUE THREAD

**Issue by ohbob** [akiarostami/sveltekit-tailwind-blog-starter#1]
First of, thank you for the template, it looks gorgeous. 

I've encountered a problem with relative images and /src/routes/blog/[slug]/+page.server.js.

I've created a file in `content/posts/test/index.md` and added `test.jpg` to the folder. 

```
---
title: Test
date: '2022-12-07'
draft: false
summary: 'This could be a test summary'
tags:
  - Test
image: https://techcrunch.com/wp-content/uploads/2017/02/gettyimages-577322170.jpg
author: Dinesh Chugtai
---

# Random testing post

This is just a test.


![my image](./test.jpg)
```

I'm getting an error.

```
Cannot read properties of undefined (reading 'author')
TypeError: Cannot read properties of undefined (reading 'author')
    at /src/routes/blog/[slug]/+page.server.js:9:53
```
With out the relative image, everything works fine. 
Any ideas ?

**Comment by akiarostami** [comment]
Thank you for the kind note. I am not done with this though, so this is not a stable version. 

About your issue, did you delete the "content/author" folder by any chance?

Also, keep in mind that you should save your images in "static/img" folder and reference to that folder as "/img/_filename". In this example, it would be ![my image](/img/test.jpg). You can't access the content folder (or any other folder besides "static") directly from markdown.

**Comment by ohbob** [comment]
No I did not delete "content/author" folder.
What I was referring to is that by using mdsvex-relative-images you can use relative path of the content md for images.
At least when you are using routes folder. I was hoping for the same outcome on "content/posts" as well. As it is pretty convenient to store the related images to the post with the post. 
 I have attached an example images.

![Screenshot 2022-12-16 at 13 34 32](https://user-images.githubusercontent.com/47858537/208089602-81ed0412-e8a0-4a25-b073-b2c456a1798a.png)
<img width="628" alt="Screenshot 2022-12-16 at 13 32 44" src="https://user-images.githubusercontent.com/47858537/208089606-2ee4e85b-dd32-42b0-8e8d-daa718dd3a93.png">

**Comment by akiarostami** [comment]
I have finished working on this template now. Using the config file, now you can easily enable / disable multi-author feature.

About the relative pictures, I installed the plug-in, but to be frank, I never used or tested it. The reason was I prefer to use Netlify CMS which uses a central directory for all images, so relative images became useless to me. But I see your point that without Netlify CMS, keeping the files in the same folder would be easier. 

Looking at your screenshot, it see a bigger issue though: it seems that you are keeping your markdown file in your routes folder, which is not how I have setup this template. All content files are under the `content` folder.

I didn't have a proper `README` file When you installed the template, but I have now. I hope that can help you understand the template.
